import type { Metadata } from "next";
import { inter } from "./styles/fonts";
import "./styles/globals.css";
import { NextAuthProvider } from "./providers/session-provider";

export const metadata: Metadata = {
  title: "Yakuza's Legacy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>{children} </NextAuthProvider>
      </body>
    </html>
  );
}
